networks:
  default:
    driver: bridge
  redis_network:
    driver: bridge
  backend_network:
    driver: bridge
  kafka_network:
    driver: bridge
volumes:
  redis_data:
  kafka_data:
  zookeeper_data:

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    volumes:
      - ./uploads:/srv/uploads
    networks:
      - default
    ports:
      - "5175:80"
  redis:
    image: redis:8-alpine
    networks:
      - redis_network
    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0 --port 6379
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${DEV_REDIS_PASSWORD}
    env_file:
      - ./backend/.env
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: dockerfile
  #     args:
  #       - APP_PORT=${PORT:-4000}
  #   volumes:
  #     - ./uploads:/srv/uploads
  #   networks:
  #     - backend_network
  #     - redis_network
  #     - kafka_network
  #   depends_on:
  #     - redis
  #   env_file:
  #     - ./backend/.env
  #   ports:
  #     - ${PORT:-4000}:4000
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    networks:
      - kafka_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: yes
    volumes:
      - zookeeper_data:/var/lib/zookeeper

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    networks:
      - kafka_network
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: "3"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka
