openapi: 3.0.3
info:
  title: Skindora API
  version: '1.0.0'
  description: API for the Skindora application, handling user authentication, management, and other core features.
  contact:
    name: Skindora Team
    email: skindora.site@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:4000
    description: Development Server

tags:
  - name: Users
    description: Operations related to user authentication, profile, and management.
  - name: Staffs
    description: Operations available only to staff and admin roles.
  - name: Reviews
    description: Operations for creating and managing product reviews.
  - name: Products
    description: Operations for viewing and managing products.
  - name: Payments
    description: Operations related to payment gateways like ZaloPay and VNPay.
  - name: Orders
    description: Operations related to creating and managing customer orders.
  - name: Carts
    description: Operations for managing the user's shopping cart.
paths:
  $ref: './paths/all-paths.yaml'

components:
  schemas:
    # --- Request Body Schemas ---
    RegisterReqBody:
      $ref: './components/schemas/RegisterReqBody.yaml'
    LoginReqBody:
      $ref: './components/schemas/LoginReqBody.yaml'
    LogoutReqBody:
      $ref: './components/schemas/LogoutReqBody.yaml'
    ForgotPasswordReqBody:
      $ref: './components/schemas/ForgotPasswordReqBody.yaml'
    VerifyForgotPasswordTokenReqBody:
      $ref: './components/schemas/VerifyForgotPasswordTokenReqBody.yaml'
    ResetPasswordReqBody:
      $ref: './components/schemas/ResetPasswordReqBody.yaml'
    VerifyEmailReqBody:
      $ref: './components/schemas/VerifyEmailReqBody.yaml'
    ChangePasswordReqBody:
      $ref: './components/schemas/ChangePasswordReqBody.yaml'
    UpdateMeReqBody:
      $ref: './components/schemas/UpdateMeReqBody.yaml'
    RefreshTokenReqBody:
      $ref: './components/schemas/RefreshTokenReqBody.yaml'
    AddToWishListReqBody:
      $ref: './components/schemas/AddToWishListReqBody.yaml'
    RemoveFromWishListReqBody:
      $ref: './components/schemas/RemoveFromWishListReqBody.yaml'
    # staff
    PaginatedProductResponse:
      $ref: './components/schemas/PaginatedProductResponse.yaml'
    Product:
      $ref: './components/schemas/Product.yaml'
    # review
    AddNewReviewReqBody:
      $ref: './components/schemas/AddNewReviewReqBody.yaml'
    UpdateReviewReqBody:
      $ref: './components/schemas/UpdateReviewReqBody.yaml'
    Review:
      $ref: './components/schemas/Review.yaml'
    ReviewSuccessResponse:
      $ref: './components/schemas/ReviewSuccessResponse.yaml'
    PaginatedReviewResponse:
      $ref: './components/schemas/PaginatedReviewResponse.yaml'
    # payment
    ZaloPayOrderReqBody:
      $ref: './components/schemas/ZaloPayOrderReqBody.yaml'
    VNPayOrderReqBody:
      $ref: './components/schemas/VNPayOrderReqBody.yaml'
    # orders
    PrepareOrderReqBody:
      $ref: './components/schemas/PrepareOrderReqBody.yaml'
    BuyNowReqBody:
      $ref: './components/schemas/BuyNowReqBody.yaml'
    CheckoutReqBody:
      $ref: './components/schemas/CheckoutReqBody.yaml'
    CancelOrderReqBody:
      $ref: './components/schemas/CancelOrderReqBody.yaml'
    ApproveRejectCancelReqBody:
      $ref: './components/schemas/ApproveRejectCancelReqBody.yaml'
    Order:
      $ref: './components/schemas/Order.yaml'
    PreparedOrderResponse:
      $ref: './components/schemas/PreparedOrderResponse.yaml'
    OrderWithDetailsResponse:
      $ref: './components/schemas/OrderWithDetailsResponse.yaml'
    PaginatedOrderResponse:
      $ref: './components/schemas/PaginatedOrderResponse.yaml'
    UpdateOrderStatusResponse:
      $ref: './components/schemas/UpdateOrderStatusResponse.yaml'
    OrderCreationResponse:
      $ref: './components/schemas/OrderCreationResponse.yaml'
    # carts
    AddToCartReqBody:
      $ref: './components/schemas/AddToCartReqBody.yaml'
    UpdateCartReqBody:
      $ref: './components/schemas/UpdateCartReqBody.yaml'
    CartResponse:
      $ref: './components/schemas/CartResponse.yaml'

    # --- Response Schemas ---
    AuthSuccessResponse:
      $ref: './components/schemas/AuthSuccessResponse.yaml'
    LoginSuccessResponse:
      $ref: './components/schemas/LoginSuccessResponse.yaml'
    GetMeSuccessResponse:
      $ref: './components/schemas/GetMeSuccessResponse.yaml'
    RefreshTokenSuccessResponse:
      $ref: './components/schemas/RefreshTokenSuccessResponse.yaml'
    MessageResponse:
      $ref: './components/schemas/MessageResponse.yaml'
    WishListResponse:
      $ref: './components/schemas/WishListResponse.yaml'
    PaginatedVoucherResponse:
      $ref: './components/schemas/PaginatedVoucherResponse.yaml'

    # --- Error Schemas ---
    ErrorValidationResponse:
      $ref: './components/schemas/ErrorValidationResponse.yaml'
    ErrorStatusResponse:
      $ref: './components/schemas/ErrorStatusResponse.yaml'
    ErrorServerResponse:
      $ref: './components/schemas/ErrorServerResponse.yaml'

    # --- Model Schemas ---
    User:
      $ref: './components/schemas/User.yaml'
    Voucher:
      $ref: './components/schemas/Voucher.yaml'
    

  securitySchemes:
    BearerAuth:
      $ref: './components/securitySchemes/BearerAuth.yaml'
  parameters:
    $ref: './parameters/all-parameters.yaml' 
