name: Backend Build

on:
  push:
    branches: 
      - develop-be
      - main
      - "feature/**"
  pull_request:
    branches: 
      - develop-be
      - main
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Build project
        run: npm run build
        working-directory: ./backend
